/**
 * Bundles the Electron main + preload scripts to CommonJS.
 *
 * tsx/Vite only handle the renderer; Electron's main process needs plain CJS on
 * disk. This uses esbuild (already a Vite dependency) so there is no extra
 * toolchain, and it runs as part of `pnpm electron:build` / `pnpm electron:dev`.
 */
import { build } from 'esbuild'
import { copyFileSync, existsSync, mkdirSync, rmSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const outdir = join(root, 'dist-electron')
const watch = process.argv.includes('--watch')

rmSync(outdir, { recursive: true, force: true })
mkdirSync(outdir, { recursive: true })

const common = {
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'cjs',
  sourcemap: true,
  external: ['electron'],
  logLevel: 'info',
}

// Both files MUST be .cjs: the package is "type": "module", so a .js output
// would be parsed as ESM and Electron's CommonJS runtime would fail on require().
const targets = [
  { ...common, entryPoints: [join(root, 'electron/main.ts')], outfile: join(outdir, 'main.cjs') },
  { ...common, entryPoints: [join(root, 'electron/preload.ts')], outfile: join(outdir, 'preload.cjs') },
]

/**
 * The runtime icons (tray + window) live next to the bundled main process, so
 * they have to be copied in on every build. They are generated by
 * `pnpm icons` from public/favicon.svg; missing ones are not fatal — the app
 * still runs, it just falls back to a blank tray icon.
 */
const icons = ['tray.png', 'icon.png']
for (const icon of icons) {
  const src = join(root, 'build', icon)
  if (!existsSync(src)) {
    console.warn(`[electron-build] build/${icon} missing — run \`pnpm icons\``)
    continue
  }
  copyFileSync(src, join(outdir, icon))
}

if (watch) {
  const { context } = await import('esbuild')
  for (const target of targets) {
    const ctx = await context(target)
    await ctx.watch()
  }
  console.log('[electron-build] watching main + preload...')
} else {
  await Promise.all(targets.map((t) => build(t)))
  console.log(`[electron-build] built to ${outdir}`)
}